import "./globals.css"
import { Karla } from "next/font/google"

const karla = Karla({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${karla.className} bg-light-gray flex min-h-screen flex-col items-center justify-center px-8`}
      >
        {children}
      </body>
    </html>
  )
}
