import "./globals.css"
import { Libre_Franklin } from "next/font/google"

const libreFranklin = Libre_Franklin({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${libreFranklin.className} flex min-h-screen flex-col items-center px-8`}
      >
        {children}
      </body>
    </html>
  )
}
